//
// AcceptInviteRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AcceptInviteRequest: Codable {

    /** Email */
    public var email: String

    public init(email: String) {
        self.email = email
    }


}

