//
// ActivationParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ActivationParameters: Codable {

    public var activationSource: String?

    public init(activationSource: String?) {
        self.activationSource = activationSource
    }

    public enum CodingKeys: String, CodingKey { 
        case activationSource = "activation_source"
    }


}

