//
// AdminUpdateUserParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AdminUpdateUserParameters: Codable {

    public enum Role: String, Codable { 
        case admin = "Admin"
        case orgController = "OrgController"
        case orgMember = "OrgMember"
        case orgOwner = "OrgOwner"
        case bot = "Bot"
        case _super = "Super"
        case user = "User"
    }
    /** Optional: Source of activation */
    public var activationSource: String?
    /** Optional: Email */
    public var email: String?
    /** Optional: First name */
    public var firstName: String?
    /** Optional: Free limit for how many yats the user may purchase */
    public var freeLimit: Int?
    /** Optional: If the user is active, updating to true triggers user activation related events */
    public var isActive: Bool?
    /** Optional: Last name */
    public var lastName: String?
    /** Optional: User password */
    public var password: String?
    /** Optional: Update the user role */
    public var role: Role?

    public init(activationSource: String?, email: String?, firstName: String?, freeLimit: Int?, isActive: Bool?, lastName: String?, password: String?, role: Role?) {
        self.activationSource = activationSource
        self.email = email
        self.firstName = firstName
        self.freeLimit = freeLimit
        self.isActive = isActive
        self.lastName = lastName
        self.password = password
        self.role = role
    }

    public enum CodingKeys: String, CodingKey { 
        case activationSource = "activation_source"
        case email
        case firstName = "first_name"
        case freeLimit = "free_limit"
        case isActive = "is_active"
        case lastName = "last_name"
        case password
        case role
    }


}

