//
// AdminNewLootBoxType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AdminNewLootBoxType: Codable {

    /** The configuration parameters for the loot box type */
    public var config: JSONValue
    /** A description for the loot box type */
    public var _description: String
    /** the name of the loot box type */
    public var name: String

    public init(config: JSONValue, _description: String, name: String) {
        self.config = config
        self._description = _description
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case config
        case _description = "description"
        case name
    }


}

