//
// Confirm2FaUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Confirm2FaUpdate: Codable {

    /** Auth code of new 2FA provider */
    public var code: String

    public init(code: String) {
        self.code = code
    }


}

