//
// Disable2FABody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Disable2FABody: Codable {

    public enum Provider: String, Codable { 
        case googleAuthenticator = "GoogleAuthenticator"
        case sms = "SMS"
    }
    /** Make this method default */
    public var disableAll: Bool
    /** Two factor authentication backend */
    public var provider: Provider?

    public init(disableAll: Bool, provider: Provider?) {
        self.disableAll = disableAll
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey { 
        case disableAll = "disable_all"
        case provider
    }


}

