//
// DisplayUserInvite.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DisplayUserInvite: Codable {

    public var activatedAt: Date?
    public var code: String
    public var createdAt: Date
    public var _id: UUID
    public var updatedAt: Date

    public init(activatedAt: Date?, code: String, createdAt: Date, _id: UUID, updatedAt: Date) {
        self.activatedAt = activatedAt
        self.code = code
        self.createdAt = createdAt
        self._id = _id
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case activatedAt = "activated_at"
        case code
        case createdAt = "created_at"
        case _id = "id"
        case updatedAt = "updated_at"
    }


}

