//
// EditRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EditRequest: Codable {

    /** Optional: hashes of records to delete */
    public var delete: [String]?
    /** Optional: list of records to add */
    public var insert: [JSONValue]?
    /** Optional: merkle root (use WASM to generate) */
    public var merkleRoot: String?
    /** Optional: signature (use WASM to generate) */
    public var signature: String?

    public init(delete: [String]?, insert: [JSONValue]?, merkleRoot: String?, signature: String?) {
        self.delete = delete
        self.insert = insert
        self.merkleRoot = merkleRoot
        self.signature = signature
    }

    public enum CodingKeys: String, CodingKey { 
        case delete
        case insert
        case merkleRoot = "merkle_root"
        case signature
    }


}

