//
// EmojiStatsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmojiStatsResponse: Codable {

    public var emojiId: String
    public var metrics: [JSONValue]

    public init(emojiId: String, metrics: [JSONValue]) {
        self.emojiId = emojiId
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey { 
        case emojiId = "emoji_id"
        case metrics
    }


}

