//
// EmojiListItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** EmojiId in canonical and display representations */

public struct EmojiListItem: Codable {

    public var canonicalFormat: String
    public var displayFormat: String

    public init(canonicalFormat: String, displayFormat: String) {
        self.canonicalFormat = canonicalFormat
        self.displayFormat = displayFormat
    }

    public enum CodingKeys: String, CodingKey { 
        case canonicalFormat = "canonical_format"
        case displayFormat = "display_format"
    }


}

