//
// Enable2FAResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Enable2FAResponse: Codable {

    /** GA secret as QR code in svg image */
    public var gaQrCodeSvg: String?
    /** GA base32 encoded secret, will be null when code is disabled */
    public var gaSecret: String?

    public init(gaQrCodeSvg: String?, gaSecret: String?) {
        self.gaQrCodeSvg = gaQrCodeSvg
        self.gaSecret = gaSecret
    }

    public enum CodingKeys: String, CodingKey { 
        case gaQrCodeSvg = "ga_qr_code_svg"
        case gaSecret = "ga_secret"
    }


}

