//
// LoadJsonResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoadJsonResponse: Codable {

    /** Data value stored by key and EmojiID */
    public var data: JSONValue

    public init(data: JSONValue) {
        self.data = data
    }


}

