//
// LoginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginRequest: Codable {

    /** Alternate identifier */
    public var alternateId: String?
    /** Email */
    public var email: String?
    /** Response from google Recaptcha */
    public var gRecaptchaResponse: String?
    /** Required: Password */
    public var password: String

    public init(alternateId: String?, email: String?, gRecaptchaResponse: String?, password: String) {
        self.alternateId = alternateId
        self.email = email
        self.gRecaptchaResponse = gRecaptchaResponse
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case alternateId = "alternate_id"
        case email
        case gRecaptchaResponse = "g_recaptcha_response"
        case password
    }


}

