//
// LookupResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LookupResponse: Codable {

    public var error: JSONValue?
    /** Records associated with EmojiID */
    public var result: [JSONValue]?
    /** Number of times emoji viewed during past month */
    public var stats: [JSONValue]
    /** Response status.  If true, the requested data will be in the result field, null otherwise */
    public var status: Bool?

    public init(error: JSONValue?, result: [JSONValue]?, stats: [JSONValue], status: Bool?) {
        self.error = error
        self.result = result
        self.stats = stats
        self.status = status
    }


}

