//
// LootBoxGenerationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LootBoxGenerationRequest: Codable {

    /** The id of the loot box type to generate */
    public var lootBoxTypeId: UUID
    /** The number of loot boxes to generate in this sample */
    public var numBoxes: Int64

    public init(lootBoxTypeId: UUID, numBoxes: Int64) {
        self.lootBoxTypeId = lootBoxTypeId
        self.numBoxes = numBoxes
    }

    public enum CodingKeys: String, CodingKey { 
        case lootBoxTypeId = "loot_box_type_id"
        case numBoxes = "num_boxes"
    }


}

