//
// MagicLinkLoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MagicLinkLoginResponse: Codable {

    public enum Status: String, Codable { 
        case active = "Active"
        case registeredInactive = "RegisteredInactive"
        case registeredActive = "RegisteredActive"
        case inactive = "Inactive"
    }
    /** Message */
    public var message: String
    /** Status of requested user after completing the login request */
    public var status: Status

    public init(message: String, status: Status) {
        self.message = message
        self.status = status
    }


}

