//
// NewUserInterestParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewUserInterestParameters: Codable {

    /** Emoji ID to express interest in */
    public var emojiId: String

    public init(emojiId: String) {
        self.emojiId = emojiId
    }

    public enum CodingKeys: String, CodingKey { 
        case emojiId = "emoji_id"
    }


}

