//
// ProxyResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProxyResult: Codable {

    /** The response from the proxied service as a Json object */
    public var json: JSONValue
    /** The response from the proxied service as a String */
    public var value: String

    public init(json: JSONValue, value: String) {
        self.json = json
        self.value = value
    }


}

