//
// ProxyCallParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProxyCallParameters: Codable {

    public enum Service: String, Codable { 
        case echo = "Echo"
        case scraper = "Scraper"
    }
    /** The data to pass through to the proxied service */
    public var data: String?
    /** &#x60;ProxyService&#x60; type */
    public var service: Service

    public init(data: String?, service: Service) {
        self.data = data
        self.service = service
    }


}

