//
// Pubkey.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A hexadecimal representation of a 256-bit public key. */

public struct Pubkey: Codable {




}

