//
// PublicLootBox.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicLootBox: Codable {

    public enum Status: String, Codable { 
        case draft = "Draft"
        case available = "Available"
        case owned = "Owned"
        case used = "Used"
    }
    /** Average score of emoji IDs in loot box */
    public var averageRhythmScore: Double
    public var createdAt: Date
    public var _id: UUID
    /** For Admin: Expanded Lootbox Type */
    public var lootboxType: JSONValue?
    /** For Admin: The type of loot box, if applicable */
    public var lootboxTypeId: UUID?
    /** For Admin: Expanded owner of a lootbox */
    public var owner: JSONValue?
    /** Loot box owner_id, required for Owned and Used loot boxes */
    public var ownerId: UUID?
    /** The prices of the yats in the box, in cents */
    public var prices: [Int]
    /** The rhythm scores of the yats in the box */
    public var scores: [Int64]
    /** Status loot box will be created in */
    public var status: Status
    /** Total value of EmojiIDs in the Loot Box */
    public var totalValue: Double
    /** Loot box yats */
    public var yats: [String]

    public init(averageRhythmScore: Double, createdAt: Date, _id: UUID, lootboxType: JSONValue?, lootboxTypeId: UUID?, owner: JSONValue?, ownerId: UUID?, prices: [Int], scores: [Int64], status: Status, totalValue: Double, yats: [String]) {
        self.averageRhythmScore = averageRhythmScore
        self.createdAt = createdAt
        self._id = _id
        self.lootboxType = lootboxType
        self.lootboxTypeId = lootboxTypeId
        self.owner = owner
        self.ownerId = ownerId
        self.prices = prices
        self.scores = scores
        self.status = status
        self.totalValue = totalValue
        self.yats = yats
    }

    public enum CodingKeys: String, CodingKey { 
        case averageRhythmScore = "average_rhythm_score"
        case createdAt = "created_at"
        case _id = "id"
        case lootboxType = "lootbox_type"
        case lootboxTypeId = "lootbox_type_id"
        case owner
        case ownerId = "owner_id"
        case prices
        case scores
        case status
        case totalValue = "total_value"
        case yats
    }


}

