//
// PublicLootBoxType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** HTTP schema for an existing LootBoxType record */

public struct PublicLootBoxType: Codable {

    /** The loot box type&#39;s configuration parameters */
    public var config: JSONValue
    /** The timestamp for when this loot box type was created */
    public var createdAt: Date
    /** A more detailed description of the loot box type */
    public var _description: String
    /** The loot box type id */
    public var _id: UUID
    /** The name of this loot box type */
    public var name: String

    public init(config: JSONValue, createdAt: Date, _description: String, _id: UUID, name: String) {
        self.config = config
        self.createdAt = createdAt
        self._description = _description
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case config
        case createdAt = "created_at"
        case _description = "description"
        case _id = "id"
        case name
    }


}

