//
// RandomResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RandomResult: Codable {

    /** Random Emoji IDs */
    public var result: [JSONValue]

    public init(result: [JSONValue]) {
        self.result = result
    }


}

