//
// RandomYatActivateBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RandomYatActivateBody: Codable {

    /** Schnorr signature nonce as a hex string */
    public var nonce: String
    /** Public key to authorize usage of a code */
    public var pubkey: String
    /** Schnorr signature as a hex with alternate_id as a challenge */
    public var signature: String
    /** Custom tracking data to be associated with a purchase */
    public var trackingData: JSONValue?

    public init(nonce: String, pubkey: String, signature: String, trackingData: JSONValue?) {
        self.nonce = nonce
        self.pubkey = pubkey
        self.signature = signature
        self.trackingData = trackingData
    }

    public enum CodingKeys: String, CodingKey { 
        case nonce
        case pubkey
        case signature
        case trackingData = "tracking_data"
    }


}

