//
// RegisterUserParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RegisterUserParameters: Codable {

    /** Optional: Whether to force activation during creation (requires UserActivate scope) */
    public var activate: Bool?
    /** Optional: Source of activation (requires UserActivate scope) */
    public var activationSource: String?
    /** Alternate identifier */
    public var alternateId: String?
    /** Email address */
    public var email: String?
    /** Optional: first name */
    public var firstName: String?
    /** Response from google Recaptcha */
    public var gRecaptchaResponse: String?
    /** Optional: last name */
    public var lastName: String?
    /** Optional: password */
    public var password: String?
    /** Required when registering with &#x60;alternate_id&#x60;, source for non custodial user */
    public var source: String?

    public init(activate: Bool?, activationSource: String?, alternateId: String?, email: String?, firstName: String?, gRecaptchaResponse: String?, lastName: String?, password: String?, source: String?) {
        self.activate = activate
        self.activationSource = activationSource
        self.alternateId = alternateId
        self.email = email
        self.firstName = firstName
        self.gRecaptchaResponse = gRecaptchaResponse
        self.lastName = lastName
        self.password = password
        self.source = source
    }

    public enum CodingKeys: String, CodingKey { 
        case activate
        case activationSource = "activation_source"
        case alternateId = "alternate_id"
        case email
        case firstName = "first_name"
        case gRecaptchaResponse = "g_recaptcha_response"
        case lastName = "last_name"
        case password
        case source
    }


}

