//
// RhythmResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RhythmResponse: Codable {

    /** The yat rhythm score, a number between 1 (least prestigious) and 100 (most prestigious) */
    public var rhythm: Int64

    public init(rhythm: Int64) {
        self.rhythm = rhythm
    }


}

