//
// SearchResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SearchResult: Codable {

    /** Alternative Emoji IDs */
    public var alternates: [JSONValue]
    /** The specific Emoji ID that the user requests */
    public var result: JSONValue

    public init(alternates: [JSONValue], result: JSONValue) {
        self.alternates = alternates
        self.result = result
    }


}

