//
// StoreJsonBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoreJsonBody: Codable {

    /** Data value allows to store any Json value, limited by 250Kb */
    public var data: JSONValue
    /** Link tag items as part of the transaction  All previously linked tags not present in new request will be deleted */
    public var linkedTags: [JSONValue]?

    public init(data: JSONValue, linkedTags: [JSONValue]?) {
        self.data = data
        self.linkedTags = linkedTags
    }

    public enum CodingKeys: String, CodingKey { 
        case data
        case linkedTags = "linked_tags"
    }


}

