//
// TokenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenResponse: Codable {

    public enum Requires2fa: String, Codable { 
        case googleAuthenticator = "GoogleAuthenticator"
        case sms = "SMS"
    }
    /** Access token */
    public var accessToken: String
    /** Refresh token,  only required for 2FA (???) */
    public var refreshToken: String
    /** Whether has 2FA enabled or not */
    public var requires2fa: Requires2fa?

    public init(accessToken: String, refreshToken: String, requires2fa: Requires2fa?) {
        self.accessToken = accessToken
        self.refreshToken = refreshToken
        self.requires2fa = requires2fa
    }

    public enum CodingKeys: String, CodingKey { 
        case accessToken = "access_token"
        case refreshToken = "refresh_token"
        case requires2fa = "requires_2fa"
    }


}

