//
// UpdateUserParameters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateUserParameters: Codable {

    /** Optional: Email */
    public var email: String?
    /** Optional: First name */
    public var firstName: String?
    /** Optional: Last name */
    public var lastName: String?

    public init(email: String?, firstName: String?, lastName: String?) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case email
        case firstName = "first_name"
        case lastName = "last_name"
    }


}

