//
// UpdateCartRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateCartRequest: Codable {

    /** New items to add to cart */
    public var items: [JSONValue]
    /** Tracking data */
    public var trackingData: JSONValue?

    public init(items: [JSONValue], trackingData: JSONValue?) {
        self.items = items
        self.trackingData = trackingData
    }

    public enum CodingKeys: String, CodingKey { 
        case items
        case trackingData = "tracking_data"
    }


}

