//
// UserInterest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserInterest: Codable {

    public var createdAt: Date
    public var emojiId: String
    public var _id: UUID
    public var updatedAt: Date
    public var userId: UUID

    public init(createdAt: Date, emojiId: String, _id: UUID, updatedAt: Date, userId: UUID) {
        self.createdAt = createdAt
        self.emojiId = emojiId
        self._id = _id
        self.updatedAt = updatedAt
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case emojiId = "emoji_id"
        case _id = "id"
        case updatedAt = "updated_at"
        case userId = "user_id"
    }


}

