//
// EmojiAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class EmojiAPI {
    /**
     List of supported emoji characters
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func emojiList(completion: @escaping ((_ data: [String]?,_ error: Error?) -> Void)) {
        emojiListWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List of supported emoji characters
     - GET /emoji
     - Result is an array of emojis `[\"ðŸ—\",\"ðŸŒˆ\"]`
     - examples: [{contentType=application/json, example=[ "", "" ]}]

     - returns: RequestBuilder<[String]> 
     */
    open class func emojiListWithRequestBuilder() -> RequestBuilder<[String]> {
        let path = "/emoji"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[String]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
