//
// LootBoxTypeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LootBoxTypeAPI {
    /**
     Create a new lootbox category
     
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createType(body: AdminNewLootBoxType, completion: @escaping ((_ data: PublicLootBoxType?,_ error: Error?) -> Void)) {
        createTypeWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a new lootbox category
     - POST /lootbox_type
     - NOTE: user must have scope `AdminLootBoxWrite`
     - API Key:
       - type: apiKey Authorization,X-Api-Key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "name" : "name",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "config" : "{}"
}}]
     
     - parameter body: (body)  

     - returns: RequestBuilder<PublicLootBoxType> 
     */
    open class func createTypeWithRequestBuilder(body: AdminNewLootBoxType) -> RequestBuilder<PublicLootBoxType> {
        let path = "/lootbox_type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<PublicLootBoxType>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     Generates a set of loot boxes
     
     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func generateLootBoxes(body: LootBoxGenerationRequest, completion: @escaping ((_ data: LootBoxSet?,_ error: Error?) -> Void)) {
        generateLootBoxesWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Generates a set of loot boxes
     - POST /lootbox_type/generate
     - NOTE: user must have scope `AdminLootBoxWrite`
     - API Key:
       - type: apiKey Authorization,X-Api-Key 
       - name: apiKey
     - examples: [{contentType=application/json, example={
  "loot_boxes" : [ "{}", "{}" ],
  "num_requested" : 0
}}]
     
     - parameter body: (body)  

     - returns: RequestBuilder<LootBoxSet> 
     */
    open class func generateLootBoxesWithRequestBuilder(body: LootBoxGenerationRequest) -> RequestBuilder<LootBoxSet> {
        let path = "/lootbox_type/generate"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<LootBoxSet>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     List all loot box categories
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTypes(completion: @escaping ((_ data: [PublicLootBoxType]?,_ error: Error?) -> Void)) {
        getTypesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     List all loot box categories
     - GET /lootbox_type
     - NOTE: user must have scope `AdminLootBoxRead`
     - API Key:
       - type: apiKey Authorization,X-Api-Key 
       - name: apiKey
     - examples: [{contentType=application/json, example=[ {
  "name" : "name",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "config" : "{}"
}, {
  "name" : "name",
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "description" : "description",
  "id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "config" : "{}"
} ]}]

     - returns: RequestBuilder<[PublicLootBoxType]> 
     */
    open class func getTypesWithRequestBuilder() -> RequestBuilder<[PublicLootBoxType]> {
        let path = "/lootbox_type"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[PublicLootBoxType]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
